<a href="https://colab.research.google.com/github/rautaditya2606/NY_TAXi_Fare/blob/main/NYC_Taxi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install opendatasets
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns
import numpy as np
import plotly.express as px
import matplotlib
%matplotlib inline
from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet, SGDRegressor
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import OneHotEncoder
import opendatasets as od
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import DecisionTreeRegressor, plot_tree, export_text
from sklearn.ensemble import RandomForestClassifier,RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score, root_mean_squared_error
from sklearn.cluster import KMeans, DBSCAN
from sklearn.decomposition import PCA
import random
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor

sns.set_style('darkgrid')
matplotlib.rcParams['font.size'] = 14
matplotlib.rcParams['figure.figsize'] = (10,6)
matplotlib.rcParams['figure.facecolor'] = '#00000000'

Collecting opendatasets
  Downloading opendatasets-0.1.22-py3-none-any.whl.metadata (9.2 kB)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from opendatasets) (4.67.1)
Requirement already satisfied: kaggle in /usr/local/lib/python3.12/dist-packages (from opendatasets) (1.7.4.5)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from opendatasets) (8.2.1)
Requirement already satisfied: bleach in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (6.2.0)
Requirement already satisfied: certifi>=14.05.14 in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (2025.8.3)
Requirement already satisfied: charset-normalizer in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (3.4.3)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (3.10)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (5.29.5)
Requirement already satisfied: python-dateutil>=2.5.3 in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (2.9.0.post0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (8.0.4)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (2.32.4)
Requirement already satisfied: setuptools>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (75.2.0)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (1.17.0)
Requirement already satisfied: text-unidecode in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (1.3)
Requirement already satisfied: urllib3>=1.15.1 in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (2.5.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (0.5.1)
Downloading opendatasets-0.1.22-py3-none-any.whl (15 kB)
Installing collected packages: opendatasets
Successfully installed opendatasets-0.1.22

In [2]:
database_url = 'https://www.kaggle.com/c/new-york-city-taxi-fare-prediction'
od.download(database_url)

Please provide your Kaggle credentials to download this dataset. Learn more: http://bit.ly/kaggle-creds
Your Kaggle username: rautaditya2606
Your Kaggle Key: ··········
Downloading new-york-city-taxi-fare-prediction.zip to ./new-york-city-taxi-fare-prediction

100%|██████████| 1.56G/1.56G [00:15<00:00, 110MB/s]

Extracting archive ./new-york-city-taxi-fare-prediction/new-york-city-taxi-fare-prediction.zip to ./new-york-city-taxi-fare-prediction

In [3]:
data_dir = '/content/new-york-city-taxi-fare-prediction/'

In [4]:
# !pip install dask-ml --quiet

In [5]:
!head {data_dir + '/train.csv'}

key,fare_amount,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count
2009-06-15 17:26:21.0000001,4.5,2009-06-15 17:26:21 UTC,-73.844311,40.721319,-73.84161,40.712278,1
2010-01-05 16:52:16.0000002,16.9,2010-01-05 16:52:16 UTC,-74.016048,40.711303,-73.979268,40.782004,1
2011-08-18 00:35:00.00000049,5.7,2011-08-18 00:35:00 UTC,-73.982738,40.76127,-73.991242,40.750562,2
2012-04-21 04:30:42.0000001,7.7,2012-04-21 04:30:42 UTC,-73.98713,40.733143,-73.991567,40.758092,1
2010-03-09 07:51:00.000000135,5.3,2010-03-09 07:51:00 UTC,-73.968095,40.768008,-73.956655,40.783762,1
2011-01-06 09:50:45.0000002,12.1,2011-01-06 09:50:45 UTC,-74.000964,40.73163,-73.972892,40.758233,1
2012-11-20 20:35:00.0000001,7.5,2012-11-20 20:35:00 UTC,-73.980002,40.751662,-73.973802,40.764842,1
2012-01-04 17:22:00.00000081,16.5,2012-01-04 17:22:00 UTC,-73.9513,40.774138,-73.990095,40.751048,1
2012-12-03 13:10:00.000000125,9,2012-12-03 13:10:00 UTC,-74.006462,40.726713,-73.993078,40.731628,1

In [6]:
selected_cols = 'fare_amount,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count'.split(',')

In [7]:
selected_cols
dtypes = {
 'fare_amount': 'float32',
 'pickup_longitude':'float32',
 'pickup_latitude':'float32',
 'dropoff_longitude':'float32',
 'dropoff_latitude':'float32',
 'passenger_count': 'uint8'
}

In [8]:
def skip_rows(row_idx):
    if row_idx == 0:
        return False
    return random.random() > 0.01
df = pd.read_csv(
    data_dir + '/train.csv',
    usecols=selected_cols,
    dtype=dtypes,
    parse_dates=['pickup_datetime'],
    skiprows=skip_rows
)

In [9]:
df

,fare_amount,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count
0,4.5,2011-04-22 23:21:03+00:00,-74.009140,40.713436,-74.002823,40.723427,3
1,11.5,2015-04-12 10:19:05+00:00,-73.979279,40.723438,-74.004608,40.746948,6
2,5.7,2011-06-09 00:53:00+00:00,-73.983055,40.722588,-73.988022,40.733738,3
3,32.5,2012-05-11 15:03:53+00:00,-73.872864,40.774105,-73.970596,40.764393,2
4,7.5,2015-03-29 13:31:25+00:00,-73.953102,40.788700,-73.956779,40.805904,1
...,...,...,...,...,...,...,...
555171,14.5,2011-12-02 18:01:00+00:00,-74.003021,40.749161,-73.959503,40.779732,2
555172,11.7,2010-01-12 13:03:00+00:00,-74.017410,40.706009,-73.991035,40.692589,1
555173,6.5,2009-10-05 13:25:40+00:00,-73.993240,40.747562,-74.005974,40.726902,1
555174,7.5,2012-12-25 22:01:05+00:00,-73.981529,40.778217,-73.962868,40.800915,2
555175,13.0,2013-09-13 22:31:01+00:00,-73.990318,40.756493,-74.000687,40.728912,1

In [10]:
test_df = pd.read_csv(data_dir + '/test.csv', parse_dates=['pickup_datetime'])

In [11]:
test_df

,key,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count
0,2015-01-27 13:08:24.0000002,2015-01-27 13:08:24+00:00,-73.973320,40.763805,-73.981430,40.743835,1
1,2015-01-27 13:08:24.0000003,2015-01-27 13:08:24+00:00,-73.986862,40.719383,-73.998886,40.739201,1
2,2011-10-08 11:53:44.0000002,2011-10-08 11:53:44+00:00,-73.982524,40.751260,-73.979654,40.746139,1
3,2012-12-01 21:12:12.0000002,2012-12-01 21:12:12+00:00,-73.981160,40.767807,-73.990448,40.751635,1
4,2012-12-01 21:12:12.0000003,2012-12-01 21:12:12+00:00,-73.966046,40.789775,-73.988565,40.744427,1
...,...,...,...,...,...,...,...
9909,2015-05-10 12:37:51.0000002,2015-05-10 12:37:51+00:00,-73.968124,40.796997,-73.955643,40.780388,6
9910,2015-01-12 17:05:51.0000001,2015-01-12 17:05:51+00:00,-73.945511,40.803600,-73.960213,40.776371,6
9911,2015-04-19 20:44:15.0000001,2015-04-19 20:44:15+00:00,-73.991600,40.726608,-73.789742,40.647011,6
9912,2015-01-31 01:05:19.0000005,2015-01-31 01:05:19+00:00,-73.985573,40.735432,-73.939178,40.801731,6
9913,2015-01-18 14:06:23.0000006,2015-01-18 14:06:23+00:00,-73.988022,40.754070,-74.000282,40.759220,6

In [12]:
df.describe()

,fare_amount,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count
count,555176.000000,555176.000000,555176.000000,555171.000000,555171.000000,555176.000000
mean,11.316721,-72.520523,39.925728,-72.518639,39.945114,1.688324
std,9.725125,13.559018,11.617429,12.976922,11.135025,1.340378
min,-44.900002,-3320.372803,-3112.299561,-3306.478516,-2528.986084,0.000000
25%,6.000000,-73.992081,40.734871,-73.991417,40.734066,1.000000
50%,8.500000,-73.981792,40.752659,-73.980179,40.753181,1.000000
75%,12.500000,-73.967072,40.767174,-73.963745,40.768059,2.000000
max,499.000000,2090.261719,3378.013428,2554.475586,3378.013428,208.000000

In [13]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found

In [14]:
train_df, val_df = train_test_split(df, test_size=0.2, random_state=42)

In [15]:
train_df.shape, val_df.shape

((444140, 7), (111036, 7))

In [16]:
train_df = train_df.dropna()
val_df = val_df.dropna()

In [17]:
list(train_df.columns)

['fare_amount',
 'pickup_datetime',
 'pickup_longitude',
 'pickup_latitude',
 'dropoff_longitude',
 'dropoff_latitude',
 'passenger_count']

In [18]:
input_cols = [
 'pickup_longitude',
 'pickup_latitude',
 'dropoff_longitude',
 'dropoff_latitude',
 'passenger_count']
target_cols = 'fare_amount'

In [19]:
train_inputs = train_df[input_cols]
train_targets = train_df[target_cols]
val_inputs = val_df[input_cols]
val_targets = val_df[target_cols]

In [20]:
def add_dateparts(df, col):
  df[col+'_year'] = df[col].dt.year
  df[col+'_month'] = df[col].dt.month
  df[col+'_day'] = df[col].dt.day
  df[col+'_weekday'] = df[col].dt.weekday
  df[col+'_hour'] = df[col].dt.hour

In [21]:
add_dateparts(train_df, 'pickup_datetime')
add_dateparts(val_df, 'pickup_datetime')
add_dateparts(test_df, 'pickup_datetime')

In [22]:
train_df

,fare_amount,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count,pickup_datetime_year,pickup_datetime_month,pickup_datetime_day,pickup_datetime_weekday,pickup_datetime_hour
486754,10.0,2014-03-23 14:10:00+00:00,-74.006119,40.737514,-73.979828,40.727119,1,2014,3,23,6,14
17632,4.5,2010-01-11 12:33:00+00:00,-73.976151,40.749023,-73.976402,40.744362,1,2010,1,11,0,12
15309,4.5,2014-09-11 01:15:00+00:00,-73.991821,40.747776,-73.990166,40.752617,4,2014,9,11,3,1
538140,5.3,2009-08-28 11:05:00+00:00,-73.968201,40.800526,-73.968803,40.790913,1,2009,8,28,4,11
155729,12.5,2009-05-01 00:36:10+00:00,-73.980385,40.751209,-73.922287,40.757648,1,2009,5,1,4,0
...,...,...,...,...,...,...,...,...,...,...,...,...
110268,5.3,2012-02-15 11:19:00+00:00,-73.964470,40.764778,-73.954552,40.778141,1,2012,2,15,2,11
259178,6.5,2013-04-22 20:16:15+00:00,-73.981041,40.728962,-73.988968,40.719097,1,2013,4,22,0,20
365838,17.5,2013-02-02 12:44:53+00:00,-73.968269,40.762691,-74.008125,40.722137,1,2013,2,2,5,12
131932,13.3,2011-07-14 08:15:17+00:00,-73.981949,40.761848,-74.008858,40.711384,1,2011,7,14,3,8
121958,13.0,2014-04-21 01:08:07+00:00,-73.980789,40.741959,-73.956558,40.748024,1,2014,4,21,0,1

In [23]:
val_df

,fare_amount,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count,pickup_datetime_year,pickup_datetime_month,pickup_datetime_day,pickup_datetime_weekday,pickup_datetime_hour
71548,17.700001,2011-12-28 18:57:00+00:00,-73.994125,40.751316,-73.955536,40.804234,1,2011,12,28,2,18
188483,5.700000,2011-03-26 23:58:38+00:00,-73.984840,40.763176,-73.978973,40.777336,1,2011,3,26,5,23
117475,10.900000,2012-03-17 19:27:33+00:00,-73.991013,40.724426,-73.987663,40.756462,1,2012,3,17,5,19
237871,27.870001,2010-07-01 22:17:16+00:00,-73.862534,40.769001,-73.976158,40.732510,1,2010,7,1,3,22
25130,6.000000,2013-10-27 18:01:48+00:00,-73.985611,40.777794,-73.977234,40.789864,1,2013,10,27,6,18
...,...,...,...,...,...,...,...,...,...,...,...,...
278463,10.500000,2014-12-02 14:05:58+00:00,-74.006523,40.717068,-73.992149,40.726532,2,2014,12,2,1,14
174793,9.000000,2013-05-27 15:56:19+00:00,-73.969376,40.753483,-73.989929,40.751667,1,2013,5,27,0,15
95670,9.700000,2010-04-13 19:33:44+00:00,-73.962067,40.805473,-73.982475,40.773048,1,2010,4,13,1,19
483551,10.900000,2010-03-02 20:04:17+00:00,-73.968292,40.765289,-73.957626,40.768494,2,2010,3,2,1,20
489453,5.500000,2013-11-16 09:29:35+00:00,-73.990448,40.757507,-74.000595,40.762726,2,2013,11,16,5,9

In [24]:
test_df

,key,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count,pickup_datetime_year,pickup_datetime_month,pickup_datetime_day,pickup_datetime_weekday,pickup_datetime_hour
0,2015-01-27 13:08:24.0000002,2015-01-27 13:08:24+00:00,-73.973320,40.763805,-73.981430,40.743835,1,2015,1,27,1,13
1,2015-01-27 13:08:24.0000003,2015-01-27 13:08:24+00:00,-73.986862,40.719383,-73.998886,40.739201,1,2015,1,27,1,13
2,2011-10-08 11:53:44.0000002,2011-10-08 11:53:44+00:00,-73.982524,40.751260,-73.979654,40.746139,1,2011,10,8,5,11
3,2012-12-01 21:12:12.0000002,2012-12-01 21:12:12+00:00,-73.981160,40.767807,-73.990448,40.751635,1,2012,12,1,5,21
4,2012-12-01 21:12:12.0000003,2012-12-01 21:12:12+00:00,-73.966046,40.789775,-73.988565,40.744427,1,2012,12,1,5,21
...,...,...,...,...,...,...,...,...,...,...,...,...
9909,2015-05-10 12:37:51.0000002,2015-05-10 12:37:51+00:00,-73.968124,40.796997,-73.955643,40.780388,6,2015,5,10,6,12
9910,2015-01-12 17:05:51.0000001,2015-01-12 17:05:51+00:00,-73.945511,40.803600,-73.960213,40.776371,6,2015,1,12,0,17
9911,2015-04-19 20:44:15.0000001,2015-04-19 20:44:15+00:00,-73.991600,40.726608,-73.789742,40.647011,6,2015,4,19,6,20
9912,2015-01-31 01:05:19.0000005,2015-01-31 01:05:19+00:00,-73.985573,40.735432,-73.939178,40.801731,6,2015,1,31,5,1
9913,2015-01-18 14:06:23.0000006,2015-01-18 14:06:23+00:00,-73.988022,40.754070,-74.000282,40.759220,6,2015,1,18,6,14

In [25]:
def haversine_vectorized(lat1, lon1, lat2, lon2):
    # Convert degrees to radians
    lat1, lon1, lat2, lon2 = map(np.radians, [lat1, lon1, lat2, lon2])

    dlat = lat2 - lat1
    dlon = lon2 - lon1
    a = np.sin(dlat / 2.0)**2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon / 2.0)**2
    c = 2 * np.arcsin(np.sqrt(a))
    km = 6371 * c
    return km

def add_trip_dist(df):
    df['trip_distance'] = haversine_vectorized(
        df['pickup_latitude'],
        df['pickup_longitude'],
        df['dropoff_latitude'],
        df['dropoff_longitude']
    )

In [26]:
add_trip_dist(train_df)
add_trip_dist(val_df)
add_trip_dist(test_df)

In [27]:
val_df.head(1)

,fare_amount,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count,pickup_datetime_year,pickup_datetime_month,pickup_datetime_day,pickup_datetime_weekday,pickup_datetime_hour,trip_distance
71548,17.700001,2011-12-28 18:57:00+00:00,-73.994125,40.751316,-73.955536,40.804234,1,2011,12,28,2,18,6.721694

In [28]:
train_df.head(1)

,fare_amount,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count,pickup_datetime_year,pickup_datetime_month,pickup_datetime_day,pickup_datetime_weekday,pickup_datetime_hour,trip_distance
486754,10.0,2014-03-23 14:10:00+00:00,-74.006119,40.737514,-73.979828,40.727119,1,2014,3,23,6,14,2.498604

In [29]:
test_df.head(1)

,key,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count,pickup_datetime_year,pickup_datetime_month,pickup_datetime_day,pickup_datetime_weekday,pickup_datetime_hour,trip_distance
0,2015-01-27 13:08:24.0000002,2015-01-27 13:08:24+00:00,-73.97332,40.763805,-73.98143,40.743835,1,2015,1,27,1,13,2.32326

In [30]:
jfk_lonlat = -73.7781, 40.6413
lga_lonlat = -73.8740, 40.7769
ewr_lonlat = -74.1745, 40.6895
met_lonlat = -73.9632, 40.7794
wtc_lonlat = -74.0099, 40.7126

In [31]:
def add_landmark_dropoff_distance(df, landmark_name, landmark_lonlat):
  lon, lat = landmark_lonlat
  df[landmark_name+'_drop_distance'] = haversine_vectorized(lon, lat, df['dropoff_longitude'], df['dropoff_latitude'])

In [32]:
def add_landmarks(a_df):
  landmarks = [('jfk', jfk_lonlat), ('lga', lga_lonlat), ('ewr', ewr_lonlat), ('met', met_lonlat), ('wtc', wtc_lonlat)]
  for name, lonlat in landmarks:
    add_landmark_dropoff_distance(a_df, name, lonlat)

In [33]:
add_landmarks(train_df)
add_landmarks(val_df)
add_landmarks(test_df)

In [34]:
def remove_outliers(df):
    return df[(df['fare_amount'] >= 1.) &
              (df['fare_amount'] <= 500.) &
              (df['pickup_longitude'] >= -75) &
              (df['pickup_longitude'] <= -72) &
              (df['dropoff_longitude'] >= -75) &
              (df['dropoff_longitude'] <= -72) &
              (df['pickup_latitude'] >= 40) &
              (df['pickup_latitude'] <= 42) &
              (df['dropoff_latitude'] >=40) &
              (df['dropoff_latitude'] <= 42) &
              (df['passenger_count'] >= 1) &
              (df['passenger_count'] <= 6)]

In [35]:
train_df = remove_outliers(train_df)

In [36]:
val_df = remove_outliers(val_df)

In [37]:
# train_df.to_parquet('train.parquet')

In [38]:
# val_df.to_parquet('val.parquet')

In [39]:
# test_df.to_parquet('test.parquet')

In [40]:
list(train_df.columns)

['fare_amount',
 'pickup_datetime',
 'pickup_longitude',
 'pickup_latitude',
 'dropoff_longitude',
 'dropoff_latitude',
 'passenger_count',
 'pickup_datetime_year',
 'pickup_datetime_month',
 'pickup_datetime_day',
 'pickup_datetime_weekday',
 'pickup_datetime_hour',
 'trip_distance',
 'jfk_drop_distance',
 'lga_drop_distance',
 'ewr_drop_distance',
 'met_drop_distance',
 'wtc_drop_distance']

In [41]:
input_cols = ['pickup_longitude',
 'pickup_latitude',
 'dropoff_longitude',
 'dropoff_latitude',
 'passenger_count',
 'pickup_datetime_year',
 'pickup_datetime_month',
 'pickup_datetime_day',
 'pickup_datetime_weekday',
 'pickup_datetime_hour',
 'trip_distance',
 'jfk_drop_distance',
 'lga_drop_distance',
 'ewr_drop_distance',
 'met_drop_distance',
 'wtc_drop_distance']

In [42]:
target_cols = 'fare_amount'

In [43]:
train_inputs = train_df[input_cols]
val_inputs = val_df[input_cols]
test_inputs = test_df[input_cols]

In [44]:
train_targets = train_df[target_cols]
val_targets = val_df[target_cols]

In [45]:
def evaluate(model):
  train_pred = model.predict(train_inputs)
  train_rmse = np.sqrt(mean_squared_error(train_pred, train_targets))
  val_pred = model.predict(val_inputs)
  val_rmse = np.sqrt(mean_squared_error(val_pred, val_targets))
  return train_pred, val_pred, train_rmse, val_rmse

In [46]:
def predict_and_submit(model, fname):
    test_preds = model.predict(test_inputs)
    sub_df = pd.read_csv(data_dir+'/sample_submission.csv')
    sub_df['fare_amount'] = test_preds
    sub_df.to_csv(fname, index=None)
    return sub_df

In [47]:
import matplotlib.pyplot as plt

def test_params(ModelClass, **params):
    model = ModelClass(**params).fit(train_inputs, train_targets)
    train_preds = model.predict(train_inputs)
    val_preds = model.predict(val_inputs)
    train_rmse = np.sqrt(mean_squared_error(train_targets, train_preds))
    val_rmse = np.sqrt(mean_squared_error(val_targets, val_preds))
    return train_rmse, val_rmse


def test_param_and_plot(ModelClass, param_name, param_values, **other_params):
    """Trains multiple models by varying the value of param_name according to param_values"""
    train_errors, val_errors = [], []
    for value in param_values:
        params = dict(other_params)
        params[param_name] = value
        train_rmse, val_rmse = test_params(ModelClass, **params)
        train_errors.append(train_rmse)
        val_errors.append(val_rmse)

    plt.figure(figsize=(10,6))
    plt.title('Overfitting curve: ' + param_name)
    plt.plot(param_values, train_errors, 'b-o')
    plt.plot(param_values, val_errors, 'r-o')
    plt.xlabel(param_name)
    plt.ylabel('RMSE')
    plt.legend(['Training', 'Validation'])

In [48]:
model4 = LGBMRegressor(num_leaves=64, max_depth=5, learning_rate=0.1, n_estimators=1000, n_jobs=-1, verbose=-1).fit(train_inputs, train_targets)

In [49]:
evaluate(model4)#3.60231

(array([10.89326262,  4.35606413,  5.08289113, ..., 18.07089086,
        15.61857685, 13.27225889]),
 array([16.22185502,  6.27756189, 11.65900728, ...,  9.93135457,
         4.59405604,  6.28597349]),
 np.float64(3.2663003672646886),
 np.float64(3.5303209541142815))

In [51]:
# best_params = {"num_leaves":64,
#                "max_depth":7,
#                "learning_rate":0.1,
#               #  "n_estimators":600,
#                "n_jobs":-1,
#                'verbose' : -1,
#                'min_data_in_leaf' : 20
#                }


# test_param_and_plot(LGBMRegressor, 'n_estimators', [300,500,700], **best_params )

In [52]:
# predict_and_submit(model4, 'xgb_submission.csv')

In [55]:
import joblib
from google.colab import files

In [59]:
joblib.dump(model4, 'nyctaxi.joblib')

['nyctaxi.joblib']

In [60]:
files.download('nyctaxi.joblib')